### ISSUE TITLE
Strict build

### ISSUE THREAD

**Issue by 3mcd** [3mcd/harmony-ecs#2]
Enable `noImplicitAny` and `strict` in tsconfig.json and put the fires out.

**Comment by ooflorent** [comment]
You could consider the full strictness package:

```js
"strict": true,
"noImplicitReturns": true,
"noPropertyAccessFromIndexSignature": true,
"noUncheckedIndexedAccess": true,
```

Also `noImplicitAny` is already set by `strict: true`.

**Comment by 3mcd** [comment]
Great idea!
